print("Let's print some worthless stuff")
print("Ye pretty worthless this stuff")
print("I'm not even sure why I'm doing this")
print("I guess I'm just trying to fill up space")
print("I'm not even sure if this is a good idea")
